print("Hello World 😊")

print("             1")
print('           2 3')
print("         4 5 6")
print("      7 8 9 10")

print("BBBBBBBBBBBBBBBBBB")                                                                                
print('BB                BBB')                                       
print("BB                  BB")                                      
print('BB                   BB')                                     
print("BB                   BB")                                     
print("BB                   BB")                                     
print('BB                   BB')                                     
print('BB                 BB')                                       
print("BBBBBBBBBBBBBBBBBBBB")                                        
print('BB                BBB')                                       
print("BB                  BB")                                      
print('BB                   BB')                                    
print("BB                   BB")                                    
print("BB                   BB")                                     
print('BB                   BB')                                     
print('BB                 BB')                                       
print("BBBBBBBBBBBBBBBBBBBB")                                        

print("                     ")

print("RRRRRRRRRRRRRRRRRR")
print('RR                RRR')
print("RR                  RR")          
print('RR                   RR')
print("RR                   RR" )                                                    
print("RR                   RR")
print('RR                   RR')
print('RR                 RR')
print("RRRRRRRRRRRRRRRRRRRR" )
print("RR   RRR")
print("RR    RRR")
print("RR      RRR")
print("RR        RRR")
print("RR           RR")
print("RR             RR")
print("RR             RRR")
print("RR               RRRR")